/** @type {import('@commitlint/types').UserConfig & { prompt: import('czg').UserConfig['prompt'] }} */
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'subject-full-stop': [0, 'never'],
    'subject-case': [0, 'never'],
  },

  prompt: {
    alias: {
      fd: 'docs: fix typos',
      ur: 'docs: update README',
    },
    messages: {
      type: '选择你要提交的类型:',
      scope: '选择一个作用域（可选）:',
      customScope: '请输入自定义的作用域:',
      subject: '填写简短精炼的变更描述:\n',
      body: '填写更加详细的变更描述（可选）。使用 "|" 换行:\n',
      breaking: '列举非兼容性重大的变更（可选）。使用 "|" 换行:\n',
      footerPrefixesSelect: '选择关联 issue 前缀（可选）:',
      customFooterPrefix: '输入自定义 issue 前缀:',
      footer: '列举关联 issue (可选) 例如: #31, #I3244:\n',
      generatingByAI: '正在通过 AI 生成你的提交简短描述...',
      generatedSelectByAI: '选择一个 AI 生成的简短描述:',
      confirmCommit: '是否提交或修改 commit?',
    },
    types: [
      { value: 'feat', name: 'feat:     ✨ 新增功能', emoji: '✨' },
      { value: 'fix', name: 'fix:      🐛 修复缺陷', emoji: '🐛' },
      { value: 'docs', name: 'docs:     📝 文档更新', emoji: '📝' },
      { value: 'style', name: 'style:    💄 代码格式（不影响功能）', emoji: '💄' },
      { value: 'refactor', name: 'refactor: ♻️  代码重构（不含修复和新功能）', emoji: '♻️' },
      { value: 'perf', name: 'perf:     ⚡️ 性能优化', emoji: '⚡️' },
      { value: 'test', name: 'test:     ✅ 测试相关', emoji: '✅' },
      { value: 'build', name: 'build:    📦️ 构建/依赖相关', emoji: '📦️' },
      { value: 'ci', name: 'ci:       🎡 持续集成', emoji: '🎡' },
      { value: 'chore', name: 'chore:    🔧 其他杂项', emoji: '🔧' },
      { value: 'revert', name: 'revert:   ⏪️ 回退代码', emoji: '⏪️' },
    ],
    useEmoji: true,
    emojiAlign: 'center',
    useAI: false,
    themeColorCode: '',
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: '以上都不是？自定义',
    emptyScopesAlias: '跳过',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [
      { value: 'closed', name: 'closed:   ISSUES 已完成' },
      { value: 'linked', name: 'linked:   关联 ISSUES' },
    ],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: '跳过',
    customIssuePrefixAlias: '自定义前缀',
    confirmColorize: true,
    minSubjectLength: 0,
    defaultBody: '',
    defaultIssues: '',
    defaultSubject: '',
  },
}
